Repository EncryFoundation/EncryWallet, pull requests merged in 2018-07, with the labels that each got.

#8 ec-284: play start
  app/controllers/HomeController.scala
  app/views/index.scala.html
  app/views/main.scala.html
  build.sbt
  conf/application.conf
  conf/logback.xml
  conf/messages
  conf/routes
  project/plugins.sbt
  public/images/favicon.png
  public/javascripts/main.js
  public/stylesheets/main.css
  test/controllers/HomeControllerSpec.scala
Labels: work in progress

#9 EC-287 Add sample routes to Play
  app/controllers/HomeController.scala
  app/controllers/WalletController.scala
  app/crypto/Base58Check.scala
  app/crypto/PrivateKey25519.scala
  app/crypto/PublicKey25519.scala
  app/crypto/Signature25519.scala
  app/models/Account.scala
  app/models/Wallet.scala
  app/services/WalletService.scala
  app/storage/LSMStorage.scala
  build.sbt
  conf/routes
  docs/api.md
  test/controllers/HomeControllerSpec.scala
  test/controllers/WalletControllerSpec.scala
  test/services/WalletServiceSpec.scala
Labels: done

#10 EC-291 Port all routes to Play
  app/controllers/TransactionController.scala
  app/controllers/WalletController.scala
  app/models/EncryProposition.scala
  app/models/Input.scala
  app/models/Proof.scala
  app/models/RegularContract.scala
  app/models/Transaction.scala
  app/models/TransactionRequests.scala
  app/models/Wallet.scala
  app/models/box/AssetBox.scala
  app/models/box/EncryBox.scala
  app/models/directives/Directive.scala
  app/models/directives/ScriptedAssetDirective.scala
  app/models/directives/TransferDirective.scala
  app/modules/MainModule.scala
  app/services/ExplorerService.scala
  app/services/TransactionService.scala
  app/services/WalletService.scala
  app/settings/Settings.scala
  build.sbt
  conf/application.conf
  conf/routes
  docs/api.md
  src/main/resources/application.conf
  src/main/scala/org/encryfoundation/wallet/Wallet.scala
  test/controllers/TransactionControllerSpec.scala
  test/controllers/WalletControllerSpec.scala
  test/services/TransactionServiceSpec.scala
  test/services/WalletServiceSpec.scala
Labels: review required

#12 ec-wallet-refactoring
  build.sbt
  conf/messages
  public/images/favicon.png
  public/javascripts/main.js
  public/stylesheets/main.css
  src/main/resources/application.conf
  src/main/scala/org/encryfoundation/wallet/Wallet.scala
  src/main/scala/org/encryfoundation/wallet/WalletApp.scala
  src/main/scala/org/encryfoundation/wallet/account/Account.scala
  src/main/scala/org/encryfoundation/wallet/actions/NetworkActions.scala
  src/main/scala/org/encryfoundation/wallet/actions/TransactionActions.scala
  src/main/scala/org/encryfoundation/wallet/actions/WalletActions.scala
  src/main/scala/org/encryfoundation/wallet/crypto/Base58Check.scala
  src/main/scala/org/encryfoundation/wallet/crypto/PrivateKey25519.scala
  src/main/scala/org/encryfoundation/wallet/crypto/PublicKey25519.scala
  src/main/scala/org/encryfoundation/wallet/crypto/Signature25519.scala
  src/main/scala/org/encryfoundation/wallet/deprecated/Implicits.scala
  src/main/scala/org/encryfoundation/wallet/deprecated/Page.scala
  src/main/scala/org/encryfoundation/wallet/deprecated/WalletActions.scala
  src/main/scala/org/encryfoundation/wallet/deprecated/WalletView.scala
  src/main/scala/org/encryfoundation/wallet/deprecated/WebServer.scala
  src/main/scala/org/encryfoundation/wallet/http/api/ApiRoute.scala
  src/main/scala/org/encryfoundation/wallet/http/api/TransactionsApiRoute.scala
  src/main/scala/org/encryfoundation/wallet/http/api/WalletApiRoute.scala
  src/main/scala/org/encryfoundation/wallet/settings/RESTApiSettings.scala
  src/main/scala/org/encryfoundation/wallet/settings/SettingsReader.scala
  src/main/scala/org/encryfoundation/wallet/settings/WalletAppSettings.scala
  src/main/scala/org/encryfoundation/wallet/transaction/EncryProposition.scala
  src/main/scala/org/encryfoundation/wallet/transaction/Input.scala
  src/main/scala/org/encryfoundation/wallet/transaction/Proof.scala
  src/main/scala/org/encryfoundation/wallet/transaction/RegularContract.scala
  src/main/scala/org/encryfoundation/wallet/transaction/Transaction.scala
  src/main/scala/org/encryfoundation/wallet/transaction/TransactionRequests.scala
  src/main/scala/org/encryfoundation/wallet/transaction/box/AssetBox.scala
  src/main/scala/org/encryfoundation/wallet/transaction/box/EncryBox.scala
  src/main/scala/org/encryfoundation/wallet/transaction/directives/Directive.scala
  src/main/scala/org/encryfoundation/wallet/transaction/directives/ScriptedAssetDirective.scala
  src/main/scala/org/encryfoundation/wallet/transaction/directives/TransferDirective.scala
  src/main/scala/org/encryfoundation/wallet/utils/ExtUtils.scala
  src/test/scala/org/encryfoundation/wallet/JsonSerializerTest.scala
Labels: review required

#13 EC-313 Make views for routes
  app/controllers/HomeController.scala
  app/controllers/TransactionController.scala
  app/controllers/ViewController.scala
  app/controllers/WalletController.scala
  app/models/Account.scala
  app/services/ExplorerService.scala
  app/services/WalletService.scala
  app/views/index.scala.html
  app/views/layout.scala.html
  app/views/main.scala.html
  app/views/message.scala.html
  app/views/payment.scala.html
  app/views/scripted.scala.html
  app/views/settings.scala.html
  app/views/wallet.scala.html
  build.sbt
  conf/application.conf
  conf/routes
  public/stylesheets/main.css
  test/controllers/HomeControllerSpec.scala
  test/services/TransactionServiceSpec.scala
Labels: done

#14 EC-327 Implement view which displays available assets of the logged in account
  app/controllers/ViewController.scala
  app/models/Input.scala
  app/models/Output.scala
  app/models/RegularContract.scala
  app/models/Transaction.scala
  app/services/ExplorerService.scala
  app/services/TransactionService.scala
  app/services/WalletService.scala
  app/views/wallet.scala.html
  test/services/TransactionServiceSpec.scala
  test/services/WalletServiceSpec.scala
Labels: review required
